# Generated by Django 5.2.14 on 2026-05-20 19:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('mortgage', 'Mortgage'), ('tax', 'Property Tax'), ('insurance', 'Insurance'), ('repairs', 'Repairs & Maintenance'), ('improvement', 'Improvement'), ('utilities', 'Utilities'), ('other', 'Other')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paid_expenses', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='properties.property')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
